In [215]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [216]:
df=pd.read_csv("chrome_reviews.csv")

In [217]:
df.head()

ID                                         Review URL  \
0  3886  https://play.google.com/store/apps/details?id=...   
1  3887  https://play.google.com/store/apps/details?id=...   
2  3888  https://play.google.com/store/apps/details?id=...   
3  3889  https://play.google.com/store/apps/details?id=...   
4  3890  https://play.google.com/store/apps/details?id=...   

                                             Text  Star  Thumbs Up  \
0                      This is very helpfull aap.     5          0   
1                                            Good     3          2   
2  Not able to update. Neither able to uninstall.     1          0   
3                                        Nice app     4          0   
4                               Many unwanted ads     1          0   

          User Name Developer Reply        Version Review Date  \
0  INDIAN Knowledge             NaN  83.0.4103.106  2020-12-19   
1  Ijeoma Happiness             NaN  85.0.4183.127  2020-12-19   
2  Priti D BtCFs-29             NaN  85.0.4183.127  2020-12-19   
3        Ajeet Raja             NaN  77.0.3865.116  2020-12-19   
4           Rams Mp             NaN   87.0.4280.66  2020-12-19   

               App ID  
0  com.android.chrome  
1  com.android.chrome  
2  com.android.chrome  
3  com.android.chrome  
4  com.android.chrome

In [218]:
import re
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7204 entries, 0 to 7203
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   ID               7204 non-null   int64 
 1   Review URL       7204 non-null   object
 2   Text             7203 non-null   object
 3   Star             7204 non-null   int64 
 4   Thumbs Up        7204 non-null   int64 
 5   User Name        7204 non-null   object
 6   Developer Reply  95 non-null     object
 7   Version          7119 non-null   object
 8   Review Date      7204 non-null   object
 9   App ID           7204 non-null   object
dtypes: int64(3), object(7)
memory usage: 562.9+ KB


In [220]:
for i in range(0,1000):
    review = re.sub('[^a-zA-Z]', ' ', df['Text'][i])
     
    # convert all cases to lower cases
    review = review.lower()
     
    # split to array(default delimiter is " ")
    review = review.split()
     
    # creating PorterStemmer object to
    # take main stem of each word
    ps = PorterStemmer()
     
    # loop for stemming each word
    # in string array at ith row   
    review = [ps.stem(word) for word in review
                if not word in set(stopwords.words('english'))]
                 
    # rejoin all string array elements
    # to create back into a string
    review = ' '.join(review) 
     
    # append each string to create
    # array of clean text
    corpus.append(review)

In [221]:
print(corpus)

['helpful aap', 'good', 'abl updat neither abl uninstal', 'nice app', 'mani unwant ad', 'app good', 'ye ye', 'awesom', 'bad app', 'mani time tri updat updat whenev tri use app freez goe back home', 'good', 'good app', 'app get updat get open say u r use old version plz updat updat', 'mostli use', 'everyth ia possibl chrome like', 'come real statu thank', 'good', 'low download speed', 'suuper', 'want download greana free fire com file', 'good news etc', 'best', 'good', 'mydeviceshavebeenhack im humbl christian know know hard need tell know two face hard take hear tri lie much world even onlin hide true tri get life without threat everyth know stori truth call car tel rick desire come see im done keep post r', 'awesom browser', 'rait crom', 'ok', 'continu awe snap fix', 'move download use', 'best fastest', 'data consum', 'phone samsung updat app', 'lag day worst even updat even updat', 'good app like everi use', 'bad', 'nice app', 'mast xnxx', 'unabl updat googl chrome app playstor', 'at

In [224]:
y=df['Star'].iloc[:1000]
y.shape

(1000,)

In [225]:
y=y.apply(lambda x:1 if x>=3 else 0)

In [226]:
y.head()

0    1
1    1
2    0
3    1
4    0
Name: Star, dtype: int64

In [261]:
from sklearn.feature_extraction.text import CountVectorizer
 
# To extract max 1500 feature.
# "max_features" is attribute to
# experiment with to get better results
cv = CountVectorizer(max_features = 1500)

# X contains corpus (dependent variable)
X = cv.fit_transform(corpus).toarray()
X.shape
X

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [263]:
import pickle
pickle.dump(cv,open("count_vectorizer.pkl", "wb"))

In [228]:
X

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [229]:
# Splitting the dataset into
# the Training set and Test set
from sklearn.model_selection import train_test_split
 
# experiment with "test_size"
# to get better results
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=10)

In [230]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [231]:
from sklearn.ensemble import RandomForestClassifier
 
# n_estimators can be said as number of
# trees, experiment with n_estimators
# to get better results
model = RandomForestClassifier(n_estimators = 501,
                            criterion = 'entropy')
                             
model.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=501)

In [232]:
pred=model.predict(X_test)

In [233]:
pred

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [234]:
from sklearn.metrics import confusion_matrix, accuracy_score
 
print(confusion_matrix(y_test, pred))
print(accuracy_score(y_test, pred))

[[ 39  22]
 [ 16 173]]
0.848


In [235]:
# predicting
y.head

<bound method NDFrame.head of 0      1
1      1
2      0
3      1
4      0
      ..
995    1
996    1
997    0
998    0
999    1
Name: Star, Length: 1000, dtype: int64>

In [236]:
X_test.reshape(-1,1)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [237]:
corpus1=[]

In [238]:
for i in range(1001, 2001):
    review = re.sub('[^a-zA-Z]', ' ', df['Text'][i])
     
    # convert all cases to lower cases
    review = review.lower()
     
    # split to array(default delimiter is " ")
    review = review.split()
     
    # creating PorterStemmer object to
    # take main stem of each word
    ps = PorterStemmer()
     
    # loop for stemming each word
    # in string array at ith row   
    review = [ps.stem(word) for word in review
                if not word in set(stopwords.words('english'))]
                 
    # rejoin all string array elements
    # to create back into a string
    review = ' '.join(review) 
     
    # append each string to create
    # array of clean text
    corpus1.append(review)

In [239]:
corpus1

['use',
 'sure yet',
 'good',
 'z',
 'jv th st k hui cu bach gf ah g kg cm get f g v kg g mx co j chi bnbh',
 'sound music voic',
 'great',
 'better app',
 'nice',
 'nice easi direct',
 'like',
 'good',
 'unabl sign use incom mail addit neg remark use becom even difficult',
 'updat red arrow sinc decemb th everi time tri updat noth happen',
 'hit updat noth happen',
 'evil adrenochrom junki',
 'help surf internet regular updat good app',
 'good',
 'faster',
 'like',
 'chang much',
 'zubair',
 'learn much take time',
 'let updat',
 '',
 'delet name phone number notif anonym messag bolth question answer back',
 'load singl page',
 'translat websit instantli english languag',
 'best',
 'view sourc complet mess sinc last updat',
 '',
 'experyin',
 'lost profil',
 'love app',
 'year',
 'good',
 'excel browser',
 'good',
 'updat',
 'app use caus download music search app make comfort thank googl pleas updat sometim make live okay',
 'app amaz',
 'hi version l ware fix shortli sorri troll',
 

In [240]:
data=pd.DataFrame(corpus1, columns=['text'])

In [241]:
data['star']=y

In [242]:
data

text  star
0                                                  use     1
1                                             sure yet     1
2                                                 good     0
3                                                    z     1
4    jv th st k hui cu bach gf ah g kg cm get f g v...     0
..                                                 ...   ...
995                                               good     1
996  man updat mobil chrome mobil show updat click ...     1
997                             one excel app use ever     0
998                                updat relat problem     0
999                                               good     1

[1000 rows x 2 columns]

In [243]:
data.loc[data['star']==0] # getting reviews for having low stars

text  star
2                                                 good     0
4    jv th st k hui cu bach gf ah g kg cm get f g v...     0
8                                                 nice     0
9                                     nice easi direct     0
12   unabl sign use incom mail addit neg remark use...     0
..                                                 ...   ...
991                                           good app     0
992  googl product among work creator need day live...     0
993                                       chrome updat     0
997                             one excel app use ever     0
998                                updat relat problem     0

[288 rows x 2 columns]

In [244]:
X1 = cv.fit_transform(data['text']).toarray()
X1.shape
X1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [245]:
X1.shape

(1000, 1295)

In [246]:
pred1=model.predict(X1[:,:1146])

In [247]:
pred1

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,

In [248]:
data['labelled']=pred1

In [249]:
data

text  star  labelled
0                                                  use     1         1
1                                             sure yet     1         1
2                                                 good     0         1
3                                                    z     1         1
4    jv th st k hui cu bach gf ah g kg cm get f g v...     0         0
..                                                 ...   ...       ...
995                                               good     1         1
996  man updat mobil chrome mobil show updat click ...     1         1
997                             one excel app use ever     0         1
998                                updat relat problem     0         1
999                                               good     1         1

[1000 rows x 3 columns]

In [250]:
final_data=data.loc[(data['star']==0) & (data['labelled']==1)]
final_data

text  star  labelled
2                                                 good     0         1
8                                                 nice     0         1
9                                     nice easi direct     0         1
12   unabl sign use incom mail addit neg remark use...     0         1
15                              evil adrenochrom junki     0         1
..                                                 ...   ...       ...
991                                           good app     0         1
992  googl product among work creator need day live...     0         1
993                                       chrome updat     0         1
997                             one excel app use ever     0         1
998                                updat relat problem     0         1

[264 rows x 3 columns]

In [251]:
final_data.reset_index(drop=True, inplace=True)
final_data

text  star  labelled
0                                                 good     0         1
1                                                 nice     0         1
2                                     nice easi direct     0         1
3    unabl sign use incom mail addit neg remark use...     0         1
4                               evil adrenochrom junki     0         1
..                                                 ...   ...       ...
259                                           good app     0         1
260  googl product among work creator need day live...     0         1
261                                       chrome updat     0         1
262                             one excel app use ever     0         1
263                                updat relat problem     0         1

[264 rows x 3 columns]

In [252]:
final_data['text'] # finally got reviews with negative rating.

0                                                   good
1                                                   nice
2                                       nice easi direct
3      unabl sign use incom mail addit neg remark use...
4                                 evil adrenochrom junki
                             ...                        
259                                             good app
260    googl product among work creator need day live...
261                                         chrome updat
262                               one excel app use ever
263                                  updat relat problem
Name: text, Length: 264, dtype: object

 import pickle
pickle.dump(model, open("nlp_classification.pkl", "wb"))